#Minecraft server properties
spawn-protection=0
max-tick-time=600000
allow-nether=true
gamemode=survival
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=900
difficulty=normal
spawn-monsters=true
broadcast-rcon-to-ops=true
op-permission-level=4
pvp=true
hardcore=false
enable-command-block=true
max-players=20
network-compression-threshold=64
max-world-size=29999984
server-port=25566
server-ip=
spawn-npcs=true
allow-flight=true
level-name=world
level-type=minecraft\:normal
view-distance=10
spawn-animals=true
white-list=true
generate-structures=true
online-mode=true
enforce-secure-profile=false
level-seed=
prevent-proxy-connections=false
motd=Kids Military Games
enable-rcon=false
