// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<tconstruct:cast_custom:3>);
recipes.remove(<thermalfoundation:material:356>);
recipes.remove(<thermalfoundation:material:355>);
recipes.remove(<thermalfoundation:material:352>);
recipes.remove(<thermalfoundation:material:327>);
recipes.remove(<thermalfoundation:material:326>);
recipes.remove(<thermalfoundation:material:325>);
recipes.remove(<thermalfoundation:material:324>);
recipes.remove(<thermalfoundation:material:323>);
recipes.remove(<thermalfoundation:material:322>);
recipes.remove(<thermalfoundation:material:321>);
recipes.remove(<thermalfoundation:material:320>);
recipes.remove(<thermalfoundation:material:33>);
recipes.remove(<thermalfoundation:material:32>);
recipes.remove(<ic2:dust:4>);// Copper Dust
recipes.remove(<ic2:dust:7>);// Gold Dust
recipes.remove(<ic2:dust:8>);// Iron Dust
recipes.remove(<ic2:dust:10>);// Lead Dust
recipes.remove(<ic2:dust:14>);// Silver Dust
recipes.remove(<ic2:dust:17>);// Tin Dust
recipes.remove(<mysticalagriculture:iridium_seeds>);
recipes.remove(<ic2:misc_resource:1>);
recipes.remove(<sonarcore:reinforcedstoneblock>);//REINFORCED STONE

//FURNACE ORE REMOVAL
furnace.remove(<*>, <ore:oreCopper>);// Copper Ore
furnace.remove(<*>, <ore:oreGold>);// Gold Ore
furnace.remove(<*>, <ore:oreIron>);// Iron Ore
furnace.remove(<*>, <ore:oreLead>);// Lead Ore
furnace.remove(<*>, <ore:oreSilver>);// Silver Ore
furnace.remove(<*>, <ore:oreTin>);// Tin Ore
furnace.remove(<*>,<actuallyadditions:block_misc:3>);//Black Quartz Ore
furnace.remove(<*>,<ore:oreOsmium>);//Osmium Ore


// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED


// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED

recipes.addShapeless(<actuallyadditions:item_water_bowl>, [<botania:waterbowl>.withTag({Fluid: {FluidName: "water", Amount: 1000}})]);
recipes.addShapeless(<botania:waterbowl>.withTag({Fluid: {FluidName: "water", Amount: 1000}}), [<actuallyadditions:item_water_bowl>]);
recipes.addShapeless(<thermalfoundation:material:64>,[<ore:dustTinyCopper>,<ore:dustTinyCopper>,<ore:dustTinyCopper>,<ore:dustTinyCopper>]);// Copper Dust
recipes.addShapeless(<thermalfoundation:material:1>,[<ore:dustTinyGold>,<ore:dustTinyGold>,<ore:dustTinyGold>,<ore:dustTinyGold>]);// Gold Dust
recipes.addShapeless(<thermalfoundation:material>,[<ore:dustTinyIron>,<ore:dustTinyIron>,<ore:dustTinyIron>,<ore:dustTinyIron>]);// Iron Dust
recipes.addShapeless(<thermalfoundation:material:67>,[<ore:dustTinyLead>,<ore:dustTinyLead>,<ore:dustTinyLead>,<ore:dustTinyLead>]);// Lead Dust
recipes.addShapeless(<thermalfoundation:material:66>,[<ore:dustTinySilver>,<ore:dustTinySilver>,<ore:dustTinySilver>,<ore:dustTinySilver>]);// Silver Dust
recipes.addShapeless(<thermalfoundation:material:65>,[<ore:dustTinyTin>,<ore:dustTinyTin>,<ore:dustTinyTin>,<ore:dustTinyTin>]);// Tin Dust

