<industrialforegoing:laser_base>.addTooltip("Works on proper dimension in modular machine for proper yields. Does not work as normal.");
<industrialforegoing:laser_drill>.addTooltip("Works on proper dimension in modular machine for proper yields. Does not work as normal.");
<calculator:conductormast>.addTooltip("Transfer rate throttled to 50 RF/tick. Designed for crafting, not free power generation.");
<modularmachinery:itemblueprint>.withTag({dynamicmachine: "modularmachinery:block_duplicator_stone"}).addTooltip("Place unchiseled block in center slot. Compatible with many chisel blocks. Block must be from Chisel mod if the block in question has variations, such as basalt.");
<modularmachinery:itemblueprint>.withTag({dynamicmachine: "modularmachinery:space_laser_drill_desh"}).addTooltip("Structure is same for all compatible dimensions, handled by Dimension Checker's NBT.");
<forestry:bog_earth>.addTooltip("Can be matured faster with a Watering Can.");
<mekanismgenerators:generator:6>.addTooltip("Power generation much lower than standard.");<forge:bucketfilled>.withTag({FluidName: "crude_oil", Amount: 1000}).addTooltip("Can craft into other oil bucket for quest.");
<ic2:dust:11>.addTooltip("Can be obtained by processing Nether Quartz in a Thermal Centrifuge, or by macerating and centrifuging Lithium Ore.");
<contenttweaker:bioenriched_circuit>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:resonated_plated_growth_lens>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:empowered_plating>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:wispy_petal>.addTooltip("Remix item, that is its use.crafttweaker.recipes.IFurnaceManager.remove(output, optionalInput); Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:bio_napalm_cell>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:life_infused_cooler>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:circuit_case>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:ultimate_tech_block>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<contenttweaker:ultimate_magic_block>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<avaritia:resource:5>.addTooltip("Remix item, that is its use. Consume quests do not work. Simply dispose of when quest is completed.");
<thermalfoundation:ore:6>.addTooltip("Can be found using the Orechid or Lens of the Miner.");
<extrautils2:machine>.withTag({Type: "extrautils2:generator_slime"}).addTooltip("Requires Slime Block in center of crafting recipe.");