moderatorsTwitch = []
moderatorsMinecraft = ["User321", "iGoodie", "BoolymanMC"]

[[streamers]]
	minecraftNick = "MC_NICK1"
	twitchNick = "TWITCH_NICK1"
	platform = "STREAMLABS"
	token = "YOUR_TOKEN_HERE"

[[streamers]]
	minecraftNick = "MC_NICK2"
	twitchNick = "TWITCH_NICK2"
	platform = "STREAMLABS"
	token = "YOUR_TOKEN_HERE"

